FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18

# Install any additional system packages you need here
# RUN apt-get update && apt-get install -y less

# Use the 'node' user from the base image
USER node
